"use client";

import { useState } from "react";
import {
  AiThinking,
  AiGeneratedContent,
  AiRationaleCallout,
  AiSuggestionCard,
  AiUncertainty,
  AiErrorState,
} from "@/components/ai";

const THINKING_LINES = [
  "Analyzing project scope...",
  "Identifying modules...",
  "Matching skills to tasks...",
  "Balancing workload across team...",
  "Generating rationale...",
];

export default function AiStatesDevPage() {
  const [suggestionVisible, setSuggestionVisible] = useState(true);
  const [retryCount, setRetryCount] = useState(0);

  return (
    <main className="min-h-screen bg-background text-foreground p-8">
      <div className="max-w-3xl mx-auto space-y-12">
        {/* Page header */}
        <div>
          <p className="text-xs font-mono text-toxic mb-1">
            /dev/ai-states — internal dev review
          </p>
          <h1 className="text-3xl font-heading font-bold text-foreground">
            AI Visual State Components
          </h1>
          <p className="text-muted-foreground mt-2 text-sm">
            All six AI state components rendered for visual review. These are
            used across the entire Paceup workspace.
          </p>
        </div>

        {/* ─── 1. AiThinking ─── */}
        <section className="space-y-3">
          <SectionLabel index={1} name="AiThinking" />
          <AiThinking statusLines={THINKING_LINES}>
            <p className="text-sm text-muted-foreground">
              The main content area is revealed once generation completes.
            </p>
          </AiThinking>
        </section>

        {/* ─── 2. AiGeneratedContent ─── */}
        <section className="space-y-3">
          <SectionLabel index={2} name="AiGeneratedContent" />
          <AiGeneratedContent>
            <p className="text-sm text-foreground leading-relaxed">
              This task breakdown was generated by Paceup AI. It identified
              three modules: Auth, Dashboard, and Submission Review — based on
              your project brief and tech stack.
            </p>
            <p className="text-sm text-muted-foreground mt-2 leading-relaxed">
              The workload was distributed to keep each member between 60–90%
              capacity over the sprint.
            </p>
          </AiGeneratedContent>
        </section>

        {/* ─── 3. AiRationaleCallout ─── */}
        <section className="space-y-3">
          <SectionLabel index={3} name="AiRationaleCallout" />
          <div className="space-y-2">
            <p className="text-sm text-foreground">
              <span className="font-medium">Implement Auth Flow</span> — assigned to Priya
            </p>
            <AiRationaleCallout>
              Assigned to Priya because she listed Next.js Auth as{" "}
              <strong className="text-foreground">Comfortable</strong> and has
              previously implemented OAuth flows in two past projects per her
              resume summary.
            </AiRationaleCallout>
          </div>
        </section>

        {/* ─── 4. AiSuggestionCard ─── */}
        <section className="space-y-3">
          <SectionLabel index={4} name="AiSuggestionCard" />
          {suggestionVisible ? (
            <AiSuggestionCard
              title="Workload imbalance detected"
              onAccept={() => setSuggestionVisible(false)}
              onDismiss={() => setSuggestionVisible(false)}
            >
              Rahul is at 38% capacity while Priya is at 112%. Consider moving
              &quot;Set up CI pipeline&quot; from Priya to Rahul — his devops
              background makes this a natural fit.
            </AiSuggestionCard>
          ) : (
            <div className="text-sm text-muted-foreground italic border border-border rounded-lg p-4">
              Suggestion accepted or dismissed.{" "}
              <button
                className="underline text-toxic hover:text-toxic/80"
                onClick={() => setSuggestionVisible(true)}
              >
                Reset
              </button>
            </div>
          )}
        </section>

        {/* ─── 5. AiUncertainty ─── */}
        <section className="space-y-3">
          <SectionLabel index={5} name="AiUncertainty" />
          <AiUncertainty>
            <p className="text-sm leading-relaxed">
              Task &quot;Design Database Schema&quot; — suggested assignee is
              Marcus, but his profile is incomplete. Confidence in this
              assignment is low; review his skills before confirming.
            </p>
          </AiUncertainty>
        </section>

        {/* ─── 6. AiErrorState ─── */}
        <section className="space-y-3">
          <SectionLabel index={6} name="AiErrorState" />
          <AiErrorState
            message={
              retryCount > 0
                ? `Retry attempt ${retryCount} — still couldn't complete. Check your AI provider key.`
                : "Couldn't generate the task breakdown. This may be a temporary issue with your AI provider."
            }
            onRetry={() => setRetryCount((c) => c + 1)}
          />
        </section>
      </div>
    </main>
  );
}

function SectionLabel({ index, name }: { index: number; name: string }) {
  return (
    <div className="flex items-center gap-3">
      <span className="flex h-6 w-6 items-center justify-center rounded-full bg-toxic/10 border border-toxic/30 text-xs font-mono text-toxic">
        {index}
      </span>
      <code className="text-sm text-muted-foreground">{name}</code>
    </div>
  );
}
